/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.aaa.data.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Dservice service. Represents a row in the &quot;DM_Dservice&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.aaa.data.model.impl.DserviceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.aaa.data.model.impl.DserviceImpl}.
 * </p>
 *
 * @author Rishikesh Dubey
 * @see Dservice
 * @see com.liferay.aaa.data.model.impl.DserviceImpl
 * @see com.liferay.aaa.data.model.impl.DserviceModelImpl
 * @generated
 */
public interface DserviceModel extends BaseModel<Dservice>, StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dservice model instance should use the {@link Dservice} interface instead.
	 */

	/**
	 * Returns the primary key of this dservice.
	 *
	 * @return the primary key of this dservice
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dservice.
	 *
	 * @param primaryKey the primary key of this dservice
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this dservice.
	 *
	 * @return the uuid of this dservice
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this dservice.
	 *
	 * @param uuid the uuid of this dservice
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the dservice ID of this dservice.
	 *
	 * @return the dservice ID of this dservice
	 */
	public long getDserviceId();

	/**
	 * Sets the dservice ID of this dservice.
	 *
	 * @param dserviceId the dservice ID of this dservice
	 */
	public void setDserviceId(long dserviceId);

	/**
	 * Returns the group ID of this dservice.
	 *
	 * @return the group ID of this dservice
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this dservice.
	 *
	 * @param groupId the group ID of this dservice
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this dservice.
	 *
	 * @return the company ID of this dservice
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this dservice.
	 *
	 * @param companyId the company ID of this dservice
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this dservice.
	 *
	 * @return the user ID of this dservice
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this dservice.
	 *
	 * @param userId the user ID of this dservice
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dservice.
	 *
	 * @return the user uuid of this dservice
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this dservice.
	 *
	 * @param userUuid the user uuid of this dservice
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this dservice.
	 *
	 * @return the user name of this dservice
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this dservice.
	 *
	 * @param userName the user name of this dservice
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this dservice.
	 *
	 * @return the create date of this dservice
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this dservice.
	 *
	 * @param createDate the create date of this dservice
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this dservice.
	 *
	 * @return the modified date of this dservice
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dservice.
	 *
	 * @param modifiedDate the modified date of this dservice
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the service title of this dservice.
	 *
	 * @return the service title of this dservice
	 */
	@AutoEscape
	public String getServiceTitle();

	/**
	 * Sets the service title of this dservice.
	 *
	 * @param serviceTitle the service title of this dservice
	 */
	public void setServiceTitle(String serviceTitle);

	/**
	 * Returns the service description of this dservice.
	 *
	 * @return the service description of this dservice
	 */
	@AutoEscape
	public String getServiceDescription();

	/**
	 * Sets the service description of this dservice.
	 *
	 * @param serviceDescription the service description of this dservice
	 */
	public void setServiceDescription(String serviceDescription);

	/**
	 * Returns the service rate of this dservice.
	 *
	 * @return the service rate of this dservice
	 */
	@AutoEscape
	public String getServiceRate();

	/**
	 * Sets the service rate of this dservice.
	 *
	 * @param serviceRate the service rate of this dservice
	 */
	public void setServiceRate(String serviceRate);

	/**
	 * Returns the service duration of this dservice.
	 *
	 * @return the service duration of this dservice
	 */
	@AutoEscape
	public String getServiceDuration();

	/**
	 * Sets the service duration of this dservice.
	 *
	 * @param serviceDuration the service duration of this dservice
	 */
	public void setServiceDuration(String serviceDuration);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.aaa.data.model.Dservice dservice);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.aaa.data.model.Dservice> toCacheModel();

	@Override
	public com.liferay.aaa.data.model.Dservice toEscapedModel();

	@Override
	public com.liferay.aaa.data.model.Dservice toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}